<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CORE OS - Settings</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="style_dashboard.css">
</head>
<body>
    <video autoplay muted loop id="bgVideo"><source src="login.mp4" type="video/mp4"></video>
    <div class="overlay"></div>
    <div class="app-container">
        <nav class="sidebar">
            <div class="logo-section"><i class='bx bxl-visual-studio icon-glow'></i><span>AZRIL IN WEBSITE</span></div>
            <ul class="nav-menu">
                <ul class="nav-menu">
    <ul class="nav-menu">
    <li><a href="dashboard.php" class="active"><i class='bx bxs-dashboard'></i> <span>Dashboard</span></a></li>
    <li><a href="profil.php"><i class='bx bxs-terminal'></i> <span>Profil</span></a></li>
    <li><a href="projects.php"><i class='bx bxs-layer'></i> <span>Projects</span></a></li>
    <li><a href="settings.php"><i class='bx bxs-layer'></i> <span>settings</span></a></li>
    <li><a href="logout.php"><i class='bx bx-log-out'></i> <span>Logout</span></a></li>
</ul>
        </nav>
        <main class="content-area">
            <header class="main-header"><h1>SYSTEM <span class="highlight">SETTINGS MATERI</span></h1></header>
            <div class="programming-list">
                <div class="prog-item"><div class="prog-text"><h3>Security Mode</h3><p>protokol pertahanan sistem yang berfungsi untuk mengatur tingkat akses dan perlindungan data dari ancaman luar maupun kesalahan internal. Dalam pengembangan web, mode ini mencakup enkripsi data, validasi input untuk mencegah serangan seperti SQL Injection, dan manajemen sesi (session) yang ketat untuk memastikan hanya pengguna sah yang bisa mengakses area sensitif. Mode ini bertindak sebagai penjaga gerbang yang secara otomatis memutus koneksi atau mengunci akses jika terdeteksi adanya aktivitas mencurigakan atau kegagalan otentikasi.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>System Color</h3><p>skema palet warna terintegrasi yang digunakan untuk memberikan identitas visual dan status fungsional pada antarmuka pengguna (UI). Warna sistem tidak hanya soal estetika, tetapi juga komunikasi; misalnya, warna Cyan atau Biru sering digunakan untuk menandai status aktif atau teknologi tinggi, Hijau untuk akses yang diizinkan (success), dan Merah untuk peringatan atau error. Pengaturan warna sistem yang konsisten membantu pengguna memahami informasi secara instan tanpa harus membaca banyak teks, sekaligus menjaga kenyamanan mata melalui kontras yang seimbang.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>System Cyber Security</h3><p>Cyber security adalah praktik melindungi sistem, jaringan, dan program dari serangan digital yang bertujuan untuk mengakses, mengubah, atau menghancurkan informasi sensitif. Secara sederhana, ini adalah upaya menjaga rumah digital agar tidak dimasuki oleh pencuri atau dirusak oleh pihak yang tidak bertanggung jawab.Keamanan siber biasanya dibangun di atas tiga pilar utama yang dikenal sebagai CIA Triad. Pertama adalah Confidentiality atau Kerahasiaan yang memastikan bahwa data hanya bisa diakses oleh orang yang berwenang. Kedua adalah Integrity atau Integritas yang menjamin bahwa data tetap akurat dan tidak diubah oleh pihak luar selama proses penyimpanan atau pengiriman. Ketiga adalah Availability atau Ketersediaan yang memastikan sistem dan data selalu dapat diakses saat dibutuhkan oleh pengguna yang sah.Dalam dunia coding dan sistem informasi, terdapat beberapa jenis ancaman yang sering terjadi. Malware merupakan perangkat lunak berbahaya seperti virus atau ransomware yang dirancang untuk merusak komputer. Phishing adalah praktik mengirim email atau pesan palsu yang menyerupai institusi resmi untuk mencuri data pribadi seperti kata sandi. Ada juga SQL Injection yang merupakan serangan pada database dengan cara memasukkan kode berbahaya ke dalam kolom input. Jika kamu melihat peta jalan belajar coding sebelumnya, keamanan siber adalah tahap lanjut atau spesialisasi. Kamu tetap harus memahami dasar-dasar jaringan untuk mengerti bagaimana data berpindah antar komputer melalui protokol seperti HTTP atau TCP/IP. Pemahaman sistem operasi terutama Linux juga sangat penting karena banyak alat keamanan dijalankan di sana. Selain itu, menguasai coding dasar seperti Python membantu kamu membaca kode serangan dan membuat sistem pertahanan yang lebih kuat.Keamanan siber bukan hanya soal teknologi, tetapi juga soal ketelitian logika yang kuat seperti pada contoh kode C++ yang kamu lihat sebelumnya. Apakah kamu ingin tahu lebih dalam tentang cara mengamankan kode program agar tidak mudah diretas</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Mysql</h3><p>MySQL adalah sistem manajemen database yang digunakan untuk menyimpan dan mengelola data secara terorganisir, seperti yang terlihat pada bagian akhir roadmap Full Stack Developer. Sintaks MySQL adalah aturan penulisan perintah agar komputer bisa memahami instruksi manipulasi data yang kita berikan.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Panduan Terminal TERMUX</h3><p>Termux adalah emulator terminal Android dan aplikasi lingkungan Linux yang bekerja langsung tanpa perlu akses root. Belajar Termux sangat berkaitan dengan materi yang ada pada roadmap Full Stack dan logika coding yang sudah kamu lihat sebelumnya, terutama pada bagian Developer Environment dan Node.js.Berikut adalah materi pembelajaran lengkap mengenai Termux Terminal secara sistematis.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Pengenalan Dan Instalasi Dasar</h3><p>Langkah awal belajar Termux dimulai dengan proses instalasi yang benar melalui F-Droid, bukan Play Store, untuk mendapatkan pembaruan versi terbaru. Materi ini mencakup pemahaman tentang antarmuka baris perintah atau Command Line Interface (CLI). Kamu harus mempelajari perintah dasar pembaruan sistem menggunakan instruksi pkg update dan pkg upgrade agar semua paket di dalam terminal berjalan dengan versi paling stabil.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Navigasi Dan System File Linux</h3><p>Karena Termux berbasis Linux, kamu wajib menguasai navigasi folder. Materi ini meliputi perintah ls untuk melihat isi folder, cd untuk berpindah direktori, dan mkdir untuk membuat folder baru. Selain itu, kamu perlu belajar cara memberikan izin akses penyimpanan internal ponsel ke dalam Termux menggunakan perintah termux-setup-storage agar Termux bisa membaca file foto atau dokumen di luar aplikasinya.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Manajemen Paket Tools</h3><p>Materi ini mengajarkan cara memasang perangkat lunak di dalam terminal. Kamu akan belajar menggunakan perintah pkg install untuk memasang berbagai tools seperti git untuk mengelola kode seperti pada gambar roadmap yang kamu unggah. Selain itu, kamu akan belajar memasang pemutar musik berbasis terminal, alat pengunduh video, atau browser berbasis teks seperti w3m.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Lingkungan Pemrograman Dan Coding</h3><p>Sesuai dengan gambar contoh kode C++ dan Python yang kamu berikan, Termux bisa digunakan untuk ngoding langsung di HP. Materi ini mencakup instalasi bahasa pemrograman seperti Python, Node.js, PHP, atau C++. Kamu juga harus belajar menggunakan editor teks berbasis terminal seperti Nano atau Vim untuk menulis baris kode program sebelum menjalankannya melalui terminal.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Otomatisasi Dan Akses Dasar</h3><p>Pada tahap mahir, kamu akan mempelajari OpenSSH untuk mengakses terminal HP kamu dari laptop atau sebaliknya. Materi ini juga mencakup penggunaan Termux:API yang memungkinkan skrip coding kamu berinteraksi dengan fitur HP seperti mengirim SMS, mengecek status baterai, atau mengambil foto melalui perintah terminal.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Dasar Termux Pemula</h3><p>Ini adalah materi pembahan daftar perintah dasar Termux secara lengkap tanpa menggunakan blok kode agar tidak ada fitur salin-tempel (copy-paste) sekali klik. Kamu bisa membacanya dan mengetiknya secara manual untuk melatih insting mengetik di terminal.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Pembaruan System</h3><p>Langkah pertama yang selalu dilakukan adalah mengetik pkg update untuk memperbarui daftar paket. Setelah itu, ketik pkg upgrade untuk menerapkan pembaruan pada semua perangkat lunak yang terpasang agar sistem tetap stabil.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Navigasi Folder</h3><p>Untuk mengetahui kamu sedang berada di folder mana, gunakan perintah pwd. Jika ingin melihat daftar file dan folder yang ada di lokasi saat ini, ketik ls. Untuk masuk ke dalam sebuah folder, gunakan perintah cd diikuti nama foldernya, misalnya cd namafolder. Jika ingin kembali ke folder sebelumnya atau naik satu tingkat, ketik cd .. (gunakan spasi setelah cd).</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Manajemen File</h3><p>Membuat folder baru bisa dilakukan dengan mengetik mkdir namafolder. Untuk membuat file kosong, gunakan perintah touch namafile.txt. Jika ingin menghapus file, ketik rm namafile, namun berhati-hatilah karena file yang dihapus di terminal tidak masuk ke tempat sampah. Untuk menghapus folder yang memiliki isi, gunakan perintah rm -rf namafolder.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Menulis Dan Edit Code</h3><p>Sebelum mulai ngoding seperti pada gambar C++ yang kamu lihat, kamu perlu memasang editor teks. Ketik pkg install nano untuk memasang editor yang ramah pemula. Setelah terpasang, kamu bisa mengedit file dengan mengetik nano namafile.cpp. Di dalam nano, kamu bisa mengetik kode secara bebas, lalu tekan tombol CTRL dan O untuk menyimpan, serta CTRL dan X untuk keluar.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Instalasi Bahasa Pemrograman</h3><p>Agar bisa menjalankan kode seperti pada roadmap Full Stack, kamu perlu memasang bahasanya. Ketik pkg install python untuk bahasa Python, pkg install nodejs untuk JavaScript, atau pkg install clang untuk compiler C++. Setelah terpasang, jalankan programmu dengan mengetik nama bahasanya diikuti nama filenya, contohnya python script.py atau ./namafile untuk hasil kompilasi C++.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Dasar Termux Pemula</h3><p>Ini adalah materi pembahan daftar perintah dasar Termux secara lengkap tanpa menggunakan blok kode agar tidak ada fitur salin-tempel (copy-paste) sekali klik. Kamu bisa membacanya dan mengetiknya secara manual untuk melatih insting mengetik di terminal.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Akses Penyimpanan Ponsel</h3><p>Secara standar, Termux terisolasi dari memori HP kamu. Agar bisa mengakses folder download atau kamera, ketik termux-setup-storage. Setelah muncul jendela konfirmasi di layar HP, klik izinkan. Sekarang kamu bisa berpindah ke memori internal dengan mengetik cd /sdcard.</p></div></div>
                <div class="prog-item"><div class="prog-text"><h3>Perintah Informasi System</h3><p>Jika ingin melihat informasi spesifikasi HP kamu melalui terminal, ketik pkg install neofetch lalu jalankan dengan mengetik neofetch. Jika ingin melihat proses apa saja yang sedang berjalan dan memakan RAM, ketik top atau pasang alat yang lebih bagus dengan mengetik pkg install htop lalu jalankan dengan mengetik htop.</p></div></div>
                                <div class="prog-item"><div class="prog-text"><h3>Fungsi Bootstrap</h3><p>Bootstrap adalah kerangka kerja (framework) CSS yang paling populer digunakan untuk mempercepat proses pembuatan tampilan website agar terlihat profesional dan rapi secara otomatis. Sesuai dengan roadmap Full Stack yang kamu lihat sebelumnya, Bootstrap biasanya dipelajari setelah kamu menguasai dasar HTML dan CSS karena framework ini menyediakan komponen siap pakai sehingga kamu tidak perlu menulis ribuan baris kode CSS dari nol Sistem Grid yang ResponsifFitur paling utama dari Bootstrap adalah sistem grid yang memungkinkan website kamu otomatis menyesuaikan diri dengan ukuran layar perangkat apa pun, mulai dari HP hingga monitor komputer. Sistem ini membagi lebar layar menjadi 12 kolom virtual. Kamu cukup menentukan berapa kolom yang ingin digunakan untuk sebuah elemen, dan Bootstrap akan mengatur tata letaknya agar tidak berantakan saat layar diperkecil Komponen Siap PakaiBootstrap menyediakan perpustakaan komponen yang sangat lengkap seperti tombol, navigasi menu (navbar), formulir, hingga kotak pesan (alerts). Kamu hanya perlu memanggil nama class yang sudah disediakan oleh Bootstrap di dalam kode HTML kamu untuk memberikan gaya visual. Sebagai contoh, jika kamu ingin membuat tombol berwarna biru yang cantik, kamu cukup menambahkan class tertentu pada tag tombol tersebut tanpa perlu mengatur warna atau jarak secara manual di file CSSKonsistensi DesainDengan menggunakan Bootstrap, tampilan setiap halaman di website kamu akan memiliki standar desain yang konsisten. Hal ini sangat membantu bagi pemula yang belum memiliki insting desain yang kuat namun ingin menciptakan produk yang terlihat modern. Framework ini juga sudah menangani masalah perbedaan tampilan antar browser seperti Chrome, Safari, dan Firefox, sehingga kodemu akan berjalan lancar di mana saja Selain urusan tampilan, Bootstrap juga dilengkapi dengan fitur interaktif berbasis JavaScript. Kamu bisa membuat menu yang bisa muncul dan hilang (dropdown), galeri gambar yang bisa bergeser (carousel), hingga jendela pop-up (modal) dengan sangat mudah. Ini sejalan dengan fase interaktif pada gambar roadmap yang kamu unggah, di mana Bootstrap membantu menjembatani antara desain statis dan fungsionalitas dinamis.</p></div></div>
                                 <div class="prog-item"><div class="prog-text"><h3>Fungsi NPM Script</h3><p>NPM atau Node Package Manager adalah pengelola paket untuk bahasa pemrograman JavaScript yang berfungsi sebagai jembatan untuk mengunduh dan mengelola pustaka (library) milik orang lain agar bisa digunakan di proyek kita sendiri. Dalam gambar roadmap Full Stack yang kamu berikan, NPM berada di posisi setelah JavaScript karena memang sangat bergantung pada ekosistem Node.js.Fungsi Utama NPMNPM bertindak sebagai gudang raksasa di mana para developer dari seluruh dunia membagikan kode mereka secara gratis. Saat kamu membangun aplikasi besar seperti yang direncanakan dalam jadwal 200 hari tersebut, kamu tidak perlu membuat semua fitur dari nol. Kamu bisa mencari fitur yang sudah jadi di NPM, seperti fitur validasi email atau enkripsi data, lalu memasangnya ke proyekmu dengan satu baris perintah sederhana.Package.json sebagai Otak ProyekSetiap kali kamu menggunakan NPM, akan ada file bernama package.json yang tercipta di dalam folder proyekmu. File ini mencatat semua daftar pustaka yang kamu gunakan beserta versinya. Hal ini sangat penting agar ketika kodemu dibagikan ke orang lain melalui Git atau GitHub, orang tersebut bisa memasang semua kebutuhan proyek yang sama hanya dengan mengetik perintah instalasi satu kali saja.Penjelasan NPM ScriptNPM Script adalah fitur di dalam file package.json yang memungkinkan kamu membuat pintasan (shortcut) untuk menjalankan perintah-perintah terminal yang panjang atau rumit. Kamu bisa memberikan nama yang mudah diingat untuk sekumpulan instruksi, sehingga proses pengembangan menjadi lebih efisien.Sebagai contoh, alih-alih mengetik perintah panjang untuk menjalankan compiler C++ atau menjalankan server Node.js setiap saat, kamu bisa membuat script bernama "start" atau "dev". Dengan begitu, kamu cukup mengetik npm start di terminal untuk menjalankan seluruh rangkaian proses tersebut secara otomatis.Kegunaan dalam Pengembangan AplikasiNPM Script sering digunakan untuk melakukan tugas-tugas otomatis seperti membersihkan folder sementara, menjalankan pengujian kode (testing), hingga proses deployment atau mengunggah kode ke server cloud seperti AWS yang ada di akhir jadwal belajarmu. Ini membantu menjaga alur kerja tetap rapi dan mengurangi risiko kesalahan manusia saat mengetik perintah di terminal secara manual.Sama seperti logika pada contoh kode C++ yang kamu lihat, NPM Script membantu mengotomatisasi proses yang berulang agar kamu bisa lebih fokus pada penulisan logika aplikasi yang sebenarnya.</p></div></div>
                                 <div class="prog-item"><div class="prog-text"><h3>Fungsi Guthub</h3><p>GitHub adalah platform berbasis cloud yang digunakan oleh para developer untuk menyimpan, mengelola, serta melacak perubahan kode pemrograman mereka secara bersama-sama. Berdasarkan roadmap Full Stack Developer yang kamu unggah, GitHub merupakan salah satu alat paling krusial yang dipelajari setelah kamu memahami dasar-dasar coding dan alat bernama Git.Penyimpanan Kode dan Version ControlFungsi utama GitHub adalah sebagai tempat penyimpanan atau repositori kode secara online. Berbeda dengan penyimpanan biasa, GitHub mencatat setiap perubahan yang kamu lakukan pada baris kode secara detail. Hal ini sangat berguna jika suatu saat kamu melakukan kesalahan penulisan kode seperti pada contoh C++ yang kamu lihat, karena kamu bisa dengan mudah mengembalikan kode ke versi sebelumnya yang masih berjalan normal.Kolaborasi dan Kerja TimGitHub memungkinkan banyak orang untuk mengerjakan satu proyek yang sama secara bersamaan tanpa saling mengganggu pekerjaan satu sama lain. Melalui fitur yang disebut Pull Request, kamu bisa memberikan kontribusi kode pada proyek orang lain atau meminta temanmu untuk meninjau kodemu sebelum digabungkan ke proyek utama. Ini adalah standar profesional yang akan kamu temui di dunia kerja nanti.Portofolio bagi DeveloperSelain sebagai alat kerja, GitHub juga berfungsi sebagai resume atau portofolio digital bagi seorang programmer. Semua proyek yang kamu buat selama jadwal belajar 200 hari dapat dipajang di profil GitHub pribadimu. Perusahaan atau klien dapat melihat seberapa konsisten kamu melakukan coding dan bagaimana kualitas logika pemrograman yang kamu miliki melalui riwayat aktivitas di platform ini.Integrasi dengan Ekosistem DeveloperSesuai dengan alur belajar yang kamu unggah, GitHub terintegrasi dengan sangat baik dengan berbagai alat lain seperti NPM, Node.js, dan layanan cloud seperti AWS atau Google Cloud. GitHub memudahkan proses otomatisasi pengiriman kode dari komputer pribadimu langsung ke server sehingga aplikasi yang kamu buat bisa diakses oleh orang banyak di internet secara otomatis.</p></div></div>
                                  <div class="prog-item"><div class="prog-text"><h3>React.js</h3><p>React.js adalah pustaka (library) JavaScript yang berfungsi khusus untuk membangun antarmuka pengguna atau tampilan depan sebuah website. Fungsinya adalah membuat website menjadi sangat cepat dan responsif karena React hanya memperbarui bagian yang berubah saja tanpa perlu memuat ulang seluruh halaman. Dengan React, kamu bisa membagi tampilan web menjadi komponen-komponen kecil yang bisa digunakan berulang kali, sehingga kode menjadi lebih rapi dan mudah dikelola.</p></div></div>
                                   <div class="prog-item"><div class="prog-text"><h3>Node.js</h3><p>Node.js berfungsi sebagai lingkungan lari (runtime) yang memungkinkan JavaScript dijalankan di luar browser, yaitu di sisi server atau komputer. Jika React menangani apa yang dilihat pengguna, Node.js menangani logika di balik layar seperti memproses data, mengatur keamanan, dan berkomunikasi dengan database. Dalam jadwal belajar 200 hari, Node.js menjadi jembatan utama untuk mengubah kamu dari sekadar pembuat tampilan menjadi pengembang aplikasi yang utuh.</p></div></div>
                                    <div class="prog-item"><div class="prog-text"><h3>Database</h3><p>Database berfungsi sebagai gudang penyimpanan data digital secara terorganisir dan permanen. Segala informasi seperti nama pengguna, kata sandi, hingga riwayat transaksi disimpan di sini agar tidak hilang saat aplikasi ditutup. Ada dua jenis database yang umum dipelajari dalam roadmap kamu, yaitu MySQL yang menggunakan tabel kaku (relasional) dan MongoDB yang lebih fleksibel dalam menyimpan data.</p></div></div>
                                     <div class="prog-item"><div class="prog-text"><h3>Developer Envirotmen</h3><p>Developer Environment adalah lingkungan kerja atau kumpulan perangkat lunak yang disiapkan di komputer kamu untuk menulis, menguji, dan menjalankan kode secara efisien. Ini mencakup pemasangan editor teks seperti Visual Studio Code, pengaturan terminal seperti yang kamu pelajari di Termux, hingga instalasi compiler bahasa pemrograman seperti pada contoh C++. Menyiapkan lingkungan yang tepat sangat penting agar proses coding berjalan lancar tanpa gangguan teknis pada sistem operasimu.Semua elemen ini bekerja saling mendukung satu sama lain untuk membentuk sebuah aplikasi web yang fungsional dan profesional.</p></div></div>
            </div>
        </main>
    </div>
</body>
</html>
